version: '3.7'
services:
  phalcon-api:
    container_name: phalcon-api
    build:
      context: '.'
      args:
        - APP_ENV=development
        - COMPOSER_NO_INTERACTION=0
    image: phalcon-api
    ports:
      - 801:80
    volumes:
      - ./app:/app
    environment:
      - LOG_STDOUT=/dev/null
      - LOG_STDERR=/dev/null
  phalcon-api-db:
    container_name: phalcon-api-db
    image: mysql:8.0
    ports:
      - 3380:3306
    environment:
      - MYSQL_DATABASE=phalcon_api
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./data/log:/var/log/mysql:rw
    command: [
      "--innodb_use_native_aio=0",
      "--log_error=/var/log/mysql/error.log",
      "--slow_query_log=1",
      "--long_query_time=1",
      "--general_log=0",
      "--general_log_file=/var/log/mysql/general.log",
      "--slow_query_log_file=/var/log/mysql/slow-query.log",
      "--log_queries_not_using_indexes=1"
    ]
