version: '3.7'
services:
  rms-app:
    container_name: rms-app
    build:
      context: '.'
      args:
        - APP_ENV=development
        - COMPOSER_NO_INTERACTION=0
    image: rms-app
    ports:
      - 801:80
    volumes:
      - ./app:/app
    environment:
      - LOG_STDOUT=/dev/null
      - LOG_STDERR=/dev/null
  rms-db:
    container_name: rms-db
    image: mysql:8.0
    ports:
      - 3380:3306
    environment:
      - MYSQL_DATABASE=rms
      - MYSQL_USER=rms
      - MYSQL_PASSWORD=rms
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
    volumes:
      - ./config/mysql/my.cnf:/root/.my.cnf:ro
      - ./config/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./data/logs/mysql:/var/log/mysql:rw
#      - ./data/mysql:/var/lib/mysql:rw