#!/bin/bash

set -e

if [ -z "$1" ]
  then
    /app/vendor/bin/php-cs-fixer fix /app/mvc --dry-run --diff --verbose
    /app/vendor/bin/php-cs-fixer fix /app/modules --dry-run --diff --verbose
    /app/vendor/bin/phpcs -p
else
  /app/vendor/bin/php-cs-fixer fix "$1" --dry-run --diff --verbose
  /app/vendor/bin/phpcs -p
fi;
