#!/bin/bash

set -e

if [ -z "$1" ]; then
  /app/vendor/bin/php-cs-fixer fix /app/mvc --dry-run --diff --verbose
  /app/vendor/bin/php-cs-fixer fix /app/db --dry-run --diff --verbose
  /app/vendor/bin/php-cs-fixer fix /app/modules --dry-run --diff --verbose
  /app/vendor/bin/phpcs -p
elif [ "$1" == "fix" ]; then
  /app/vendor/bin/phpcbf -p
else
  /app/vendor/bin/php-cs-fixer fix "$1" --dry-run --diff --verbose
  /app/vendor/bin/phpcs -p "$1"
fi;
